### ISSUE TITLE
duplicate tab

### ISSUE THREAD

**Issue by guanhh** [dotnet/EntityFramework.Docs.zh-cn#85] opened 2020-11-30 02:57 UTC
[在此处输入反馈]

![image](https://user-images.githubusercontent.com/32925156/100564008-be3fd800-32fa-11eb-8678-e663abc8a815.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a4381838-81bb-52c6-d921-f8b9ae8163d2
* Version Independent ID: 892a8dd8-7a63-ce0b-de20-27e92b88f971
* Content: [实体属性-EF Core](https://docs.microsoft.com/zh-cn/ef/core/modeling/entity-properties?tabs=data-annotations#feedback)
* Content Source: [entity-framework/core/modeling/entity-properties.md](https://github.com/dotnet/EntityFramework.Docs.zh-cn/blob/live/entity-framework/core/modeling/entity-properties.md)
* Product: **entity-framework**
* Technology: **entity-framework-core**
* GitHub Login: @roji
* Microsoft Alias: **avickers**

**Comment by roji** [comment] 2020-11-30 06:38
Duplicate of https://github.com/dotnet/EntityFramework.Docs/issues/2900

**Comment by JasonCard** [comment] 2020-12-01 20:14
Thank you for reporting this issue and I'm following up.

**Comment by Rick-Anderson** [comment] 2021-02-03 01:11
@JasonCard can we close this?

**Comment by JasonCard** [comment] 2021-02-03 22:58
@Rick-Anderson We're still waiting for the bug to be addressed, so keep it open for now.

**Comment by roji** [comment] 2021-02-04 10:45
I suggest we close these language-specific ones in favor of dotnet/EntityFramework.Docs#2900, which we can reopen if we want?

**Comment by Rick-Anderson** [comment] 2021-02-04 21:21
@roji, @JasonCard owns this repo. I've recommend the same in other repo's. I'm guessing he wants to keep this bug open those who opened it and are following it are notified.

**Comment by JasonCard** [comment] 2021-02-04 21:56
Yes, I'll close the ones for loc repos once they are fixed.

**Comment by JasonCard** [comment] 2021-02-10 01:44
This issue is now fixed :)

**Closed by JasonCard** 2021-02-10 01:44 UTC
